### ISSUE TITLE
add support for sendmail()

### ISSUE THREAD

**Issue by oliviamriley** [DaylightingSociety/DeadManSwitch#2]
nodemailer supports the sendmail() utility, letting a user send smtp from their own pc/ip. 

to add support for this we need to setup new config options and some user control 
we'll send the setting of x provider vs sendmail over ipc from the render process

**Comment by milo-trujillo** [comment]
It looks like the sendmail() utility [directly calls the `sendmail` program](http://nodemailer.com/transports/sendmail/).

That requires the user already has sendmail installed and configured, which is pretty unlikely. Could we instead [include an SMTP client](https://github.com/emailjs/emailjs-smtp-client) so we can talk directly to the mail server instead of going through `sendmail`?

**Comment by oliviamriley** [comment]
duplicate of #9
