### ISSUE TITLE
add support for direct sending of emails

### ISSUE THREAD

**Issue by oliviamriley** [DaylightingSociety/DeadManSwitch#9]
we should be able to use the user's computer as an smtp client and send it from there instead of hooking into some other provider like gmail. 

i think nodemailer's [smtp-connection](https://nodemailer.com/extras/smtp-connection/) would be the best choice in this case.

**Comment by milo-trujillo** [comment]
I'm a little confused as to what you mean here. An SMTP client will still need to connect to an SMTP server such as gmail, so I'm unclear what change you're describing.

**Comment by oliviamriley** [comment]
my idea was to just connect to the recipient's incoming mail server over tcp and send the message that way, without going through the intermediate servers and infrastructure. 

after reading [this article](https://gist.github.com/andris9/3972378), i'm aware of a few drawbacks, mainly that our mail will likely be seen as spam and dropped. 

im mainly trying to address the use case where a user doesn't know want to make a new account or give us their credentials. in that case, they should be able to send mail straight from their computer, while being aware of the risks. 

thoughts?

**Comment by milo-trujillo** [comment]
Yeah, most email providers are going to reject mail that comes from home Internet connections, or will be more likely to flag it as spam since it won't have proper DKIM or SPF headers. It also technically requires forging email, since you'll need to make up a "reply" address when crafting the email, for an address and domain you don't actually control. In addition, some ISPs (looking at you, Comcast) drop all traffic on port 25, so you literally cannot send emails in this way.

This also means you'll either need the user to fill in the server details for the mail server we'll be delivering to, or we'd need to do a DNS lookup for the MX record of the domain name they're sending to, and assume SMTP on port 25 to that mail server (pretty safe assumption).

All in all, I think this feature will be a lot of work for mail that will likely bounce or be marked as spam, if we can even send mail at all. Maybe instead we can direct the user towards sites that make it really easy to spin up new email accounts anonymously?

**Comment by oliviamriley** [comment]
I agree that it's a lot of work and likely not worth it. 

I'm having trouble finding those kinds of sites. Do you have any in mind?

**Comment by milo-trujillo** [comment]
We can investigate temporary email services like [Guerrilla Mail](https://www.guerrillamail.com/) and [Sharks with Lasers](https://www.sharklasers.com/), but they're both built to be accessed over the web and may not support SMTP relaying. Then there's the 4Chan email provider, [Cock.li](https://cock.li/server) which is (more than) a little unsavory, but absolutely supports connecting over SMTP. I'm sure there are more, but those are the ones I know off the top of my head.

**Comment by oliviamriley** [comment]
nice, i'll look into those!

**Comment by milo-trujillo** [comment]
Ah, right! Much more appropriate, there's [RiseUp](https://riseup.net/en/email) and [ProtonMail](https://protonmail.com/), both of which should fit our needs pretty well.

**Comment by oliviamriley** [comment]
After looking at those options, RiseUp is the clear winner. ProtonMail doesn't support SMTP, nor do the two anonymous webmail clients, and the 4Chan one is... bad.

**Comment by milo-trujillo** [comment]
Agreed! Let's make sure to include RiseUp in the pull-down of default mail providers (See #7), and then add instructions to make it easy for users to register new accounts there if they (understandably) don't want to give us real login credentials.
